# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8f44e8a993227cbea6d4e76133191e8eb21b2a62d8ee76d87f5b6ac26912d4924db1de735882c2b7304fbc8148296d600b9d3a424c74f13fdbf7b47c9724196d

test:
  secret_key_base: 1cdfc292979ca3a4d17a877560c03f32f7c1320a1824f716612e9f7f946dd27919cbe3aa4a2023a48291a64825ed122c917a24d140c7a7ad159b829b9361e3df

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
